from fastapi import FastAPI, HTTPException, Depends, status
from pydantic import BaseModel, EmailStr
from sqlmodel import Session
from sqlalchemy.exc import IntegrityError
from contextlib import asynccontextmanager
from src.services.account_service import create_mock_account
from src.services.database import create_db_and_tables, get_db
from src.models.user import User
from src.auth.Account import Account
from fastapi.middleware.cors import CORSMiddleware

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Run when server starts
    print("Initializing database...")
    create_db_and_tables()
    yield
    # runs when server shuts down
    print("Shutting down...")

# create fastapi instance
app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Declare the UserSignUp Model
class UserSignUp(BaseModel):
    username: str
    email: EmailStr
    password: str
    first_name: str
    last_name: str
    
account_worker = Account()
    
# Create User endpoint
@app.post("/accounts/create", status_code=status.HTTP_201_CREATED)
async def register_user(user_data: UserSignUp, db: Session = Depends(get_db)):
    try:
        # Validate & hash
        # checks for length, special chars, etc. and raises ValueError if fails
        account_worker.create_account(user_data.username, user_data.password)
        
        # Get the hash generated by Account
        hashed_pw = account_worker.ph.hash(user_data.password)
        
        # Save to supabase
        new_user = User(
            username=user_data.username,
            email=user_data.email,
            hashed_password=hashed_pw
        )
        db.add(new_user)
        try:
            db.commit()
        except IntegrityError:
            db.rollback()
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Username or Email already registered"
            )
        db.refresh(new_user)
        
        # register to alpaca
        new_alpaca_account = create_mock_account(
            user_email=user_data.email,
            first_name=user_data.first_name,
            last_name=user_data.last_name
        )
        
        if new_alpaca_account is None:
            # delete user if alpaca is down
            db.delete(new_user)
            db.commit()
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY, 
                detail="Alpaca service is currently unavailable"
            )
        
        # update supabase with alpaca id
        new_user.alpaca_account_id = str(new_alpaca_account.id)
        db.add(new_user)
        db.commit()
        
        return {
            "status": "success",
            "message": "Mockvestor account created",
            "alpaca_account_id": new_alpaca_account.id
        }
    
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))
    except HTTPException:
        # Re-raise the HTTPExceptions we manually triggered above
        raise
    except Exception as e:
        # Something crashed somwhere
        raise HTTPException(status_code=500, detail="Internal Server Error")