from fastapi import FastAPI, HTTPException, Depends, status
from pydantic import BaseModel, EmailStr, Field
from sqlmodel import Session, select
from sqlalchemy.exc import IntegrityError
from contextlib import asynccontextmanager
from src.core.logger import logger
from src.services.account_service import create_mock_account, deposit_to_mock_account, get_account_holdings, get_portfolio_value, submit_mock_order, get_live_quote
from src.services.database import create_db_and_tables, get_db
from src.models.user import User
from src.models.transaction import Transaction
from src.auth.Account import Account
from fastapi.middleware.cors import CORSMiddleware
from src.auth.jwt_handler import create_access_token, get_current_user_id
from src.services.daily_fetch import get_historical_chart_data
from src.services.trade_feedback import Feedback

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Run when server starts
    logger.debug("Initializing database...")
    create_db_and_tables()
    yield
    # Runs when server shuts down
    logger.debug("Shutting down...")

# Create fastapi instance
app = FastAPI(lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Declare the UserSignUp Model
class UserSignUp(BaseModel):
    username: str
    email: EmailStr
    password: str
    first_name: str
    last_name: str

account_worker = Account()

# Create User endpoint
@app.post("/accounts/create", status_code=status.HTTP_201_CREATED)
async def register_user(user_data: UserSignUp, db: Session = Depends(get_db)):
    try:
        # Validate & hash
        # checks for length, special chars, etc. and raises ValueError if fails
        account_worker.create_account(user_data.username, user_data.password)

        # Get the hash generated by Account
        hashed_pw = account_worker.ph.hash(user_data.password)

        # Save to supabase
        new_user = User(
            username=user_data.username,
            email=user_data.email,
            hashed_password=hashed_pw,
            first_name=user_data.first_name,
            last_name=user_data.last_name
        )
        db.add(new_user)
        try:
            db.commit()
        except IntegrityError:
            db.rollback()
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Username or Email already registered"
            )
        db.refresh(new_user)

        # Register to alpaca
        try:
            new_alpaca_account = create_mock_account(
                user_email=user_data.email,
                first_name=user_data.first_name,
                last_name=user_data.last_name
            )
        except Exception as alpaca_error:
            logger.info(f"ALPACA CREATION FAILED - {str(alpaca_error)}")

            # Delete user from database since broker account failed
            db.delete(new_user)
            db.commit()

            # Stop the request and send the error to frontend
            raise HTTPException(
                status_code=502,
                detail=f"Alpaca Error: {str(alpaca_error)}"
            )

        if new_alpaca_account is None:
            # Delete user if alpaca is down
            db.delete(new_user)
            db.commit()
            raise HTTPException(
                status_code=status.HTTP_502_BAD_GATEWAY,
                detail="Alpaca service is currently unavailable"
            )

        # Update supabase with alpaca id
        new_user.alpaca_account_id = str(new_alpaca_account.id)
        db.add(new_user)
        db.commit()

        # Fund the new account
        try:
            deposit_to_mock_account(
                alpaca_account_id=new_alpaca_account.id,
                first_name=user_data.first_name,
                last_name=user_data.last_name,
                amount="50000.00"
            )

        except Exception as e:
            logger.info(f"DEPOSIT ERROR: {str(e)}")

        return {
            "status": "success",
            "message": "User created and funded successfully",
            "user_id": str(new_user.id),
            "username": new_user.username,
            "alpaca_account_id": new_alpaca_account.id
        }

    except HTTPException:
        # Re-raise the HTTPExceptions we manually triggered above
        raise
    except Exception as e:
        # Something crashed somwhere
        logger.info(f"HTTP Exception: Status Code 500 - Internal Server Error")
        raise HTTPException(status_code=500, detail="Internal Server Error")

class UserLogin(BaseModel):
    username: str
    password: str

@app.post("/accounts/login", status_code=status.HTTP_200_OK)
async def login_user(login_data: UserLogin, db: Session = Depends(get_db)):
    # Validate login data
    is_valid = account_worker.login(login_data.username, login_data.password, db)

    if not is_valid:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password"
        )

    # Look up the user's alpaca account id
    statement = select(User).where(User.username == login_data.username)
    db_user = db.scalars(statement).first()

    # Generate the JWT
    access_token = create_access_token(user_id=str(db_user.id))

    return {
        "status": "success",
        "message": "Login successful",
        "user_id": str(db_user.id),
        "username": db_user.username,
        "alpaca_account_id": db_user.alpaca_account_id,
        "access_token": access_token,
        "token_type": "bearer"
    }

class DepositRequest(BaseModel):
    amount: float

@app.post("/accounts/{user_id}/deposit")
async def deposit_funds(user_id: str, deposit_data: DepositRequest, db: Session = Depends(get_db), current_user_id: str = Depends(get_current_user_id)):
    # Look up the user's alpaca account id
    statement = select(User).where(User.username == user_id)
    db_user = db.scalars(statement).first()

    if not db_user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    """
    Security Check: Does the UUID inside the token match the
    UUID of the requested account?
    """
    if current_user_id != str(db_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to modify this account"
        )

    if not db_user.alpaca_account_id:
        raise HTTPException(
            status_code=404,
            detail="Brokerage account not found"
        )

    try:
        # Pass the data to alpaca
        deposit_to_mock_account(
            alpaca_account_id=db_user.alpaca_account_id,
            first_name=db_user.first_name,
            last_name=db_user.last_name,
            amount=deposit_data.amount
        )

        return {
            "status": "success",
            "message": f"Successfully deposited ${deposit_data.amount}"
        }

    except Exception as e:
        logger.info(f"DEPOSIT ERROR: {str(e)}")
        raise HTTPException(status_code=502, detail="Transfer failed")

@app.get("/accounts/{user_id}/portfolio")
async def get_portfolio(user_id: str, db: Session = Depends(get_db), current_user_id: str = Depends(get_current_user_id)):
    # Look up the user by the username
    statement = select(User).where(User.username == user_id)
    db_user = db.scalars(statement).first()

    if not db_user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    # Security Check
    if current_user_id != str(db_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to view this account"
        )

    if not db_user.alpaca_account_id:
        raise HTTPException(
            status_code=404,
            detail="Brokerage account not found"
        )

    try:
        portfolio_data = get_portfolio_value(db_user.alpaca_account_id)
        holdings_data = get_account_holdings(db_user.alpaca_account_id)

        # Package it for the frontend
        return {
            "status": "success",
            "portfolio": portfolio_data,
            "holdings": holdings_data
        }

    except Exception as e:
        logger.info(f"PORTFOLIO ERROR: {str(e)}...failed to fetch portfolio data.")
        raise HTTPException(
            status_code=502,
            detail="Failed to fetch portfolio data"
        )

class OrderRequest(BaseModel):
    symbol: str = Field(..., example="AAPL")
    qty: float = Field(..., gt=0, example=1.0)
    side: str = Field(..., pattern="^(buy|sell)$", example="buy")

@app.post("/accounts/{user_id}/orders")
async def place_order(user_id: str, order_data: OrderRequest, db: Session = Depends(get_db), current_user_id: str = Depends(get_current_user_id)):
    # Security Check
    statement = select(User).where(User.username == user_id)
    db_user = db.scalars(statement).first()

    if not db_user:
        raise HTTPException(
            status_code=404,
            detail="User not found"
        )

    if current_user_id != str(db_user.id):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Not authorized to trade on this account"
        )

    if not db_user.alpaca_account_id:
        raise HTTPException(
            status_code=400,
            detail="No brokerage account linked"
        )

    try:
        # Submit the order
        order = submit_mock_order(
            alpaca_account_id=db_user.alpaca_account_id,
            symbol=order_data.symbol,
            qty=order_data.qty,
            side=order_data.side
        )

        new_transaction = Transaction(
            user_id=db_user.id,
            alpaca_order_id=str(order.id),
            symbol=order.symbol,
            qty=float(order.qty),
            side=order.side,
            status=order.status
        )
        db.add(new_transaction)
        db.commit()

        return {
            "status": "success",
            "order_id": str(order.id),
            "symbol": order.symbol,
            "qty": float(order.qty),
            "side": order.side,
            "order_status": order.status
        }

    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Broker rejection: {str(e)}"
        )

@app.get("/markets/quote/{ticker}")
async def fetch_live_quote(
    ticker: str,
    current_user_id: str = Depends(get_current_user_id)
):
    trade_feedback = Feedback()
    try:
        quote_data = get_live_quote(ticker)
        risk_pred, risk_level, risk_base = trade_feedback.predict_risk(ticker)
        day_risk = risk_pred['1d'][3]
        day_vol = f"{risk_pred['1d'][0]:.2%}"
        day_expLow = f"{risk_pred['1d'][1]:.2f}"
        day_expHigh = f"{risk_pred['1d'][2]:.2f}"
        week_risk = risk_pred['5d'][3]
        week_vol = f"{risk_pred['5d'][0]:.2%}"
        week_expLow = f"{risk_pred['5d'][1]:.2f}"
        week_expHigh = f"{risk_pred['5d'][2]:.2f}"
        month_risk = risk_pred['21d'][3]
        month_vol = f"{risk_pred['21d'][0]:.2%}"
        month_expLow = f"{risk_pred['21d'][1]:.2f}"
        month_expHigh = f"{risk_pred['21d'][2]:.2f}"

        return {
            "status": "success",
            "data": quote_data,
            "day_risk": day_risk,
            "day_vol": day_vol,
            "day_exp_low": day_expLow,
            "day_exp_high": day_expHigh,
            "week_risk": week_risk,
            "week_vol": week_vol,
            "week_exp_low": week_expLow,
            "week_exp_high": week_expHigh,
            "month_risk": month_risk,
            "month_vol": month_vol,
            "month_exp_low": month_expLow,
            "month_exp_high": month_expHigh,
            "risk_level": risk_level
        }
    except Exception as e:
        raise HTTPException(
            status_code=404,
            detail=f"Failed to fetch quote: {str(e)}"
        )

@app.get("/market/historical/{ticker}")
async def fetch_historical_data(
    ticker: str,
    db: Session = Depends(get_db),
    current_user_id: str = Depends(get_current_user_id)
):
    historical_data = get_historical_chart_data(db, ticker)

    if not historical_data:
        raise HTTPException(
            status_code=404,
            detail=f"No historical data found for {ticker.upper()}"
        )

    return {
        "status": "success",
        **historical_data
    }